name: hello-world
description: say Hello World

inputs:
  label-prefix:
    description: prefix of label to filter
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
